# Conclusion

## Question 1 and 3

In the year of 2020, we found that the top 5 main reasons that cost most death is "COVID-19", "Atherosclerotic heart disease", "Bronchus or lung, unspecified - Malignant neoplasms", "Alzheimer disease, unspecified", and "Chronic obstructive pulmonary disease, unspecified". And this five disease takes up 6% of total death. And among this five causes, the death caused by covid-19 is tiwce as much as other four. For the situation of each state, the top five state that have most death is California, Texas, Florida, New York, Pennsylvanina. And the top five state that have highest death rate is West Virginia, Mississippi, Alabama, Ohio, Pennsylvanina. This is because the population of each state varies.

## Question 2 and 4

For question 2, we use time series plot to show the trend of top 5 disease, excluding COVID-19, in recent 10 years for both gender. From the result, we would say people should care more about the "Atherosclerotic heart disease" and "Chronic obstructive pulmonary disease, unspecified
M" diseases.

For question 4, we used mosaic plot and decision tree plot to analyze the top 1 cause of death --"Atherosclerotic heart disease". Our two plots shows the same result that male, Black or African American and White, and old people are more risky in this disease. 

## Conclusion for the project

Our limitation here would be that we cannot download all the data using the filters as many as we want on the CDC website. This limitation results in the change of our questions, which we used to analyze on the top 10 causes of death for the previous 10 years. 

However, this limitation does not limit our ability to integrate and analyze data. For the alternative solution, we download the data using the same filters but different criteria and combine two datasets to get what we want for that question. we think this would be the lesson we learned from this project -- how to get integrated data. 

In the future, we would be emphasis on the data collection and data cleaning processes, since we know how important would a meaningful and cleaning dataset be to our plots. 